Repository MLH-Fellowship/acadivity, pull requests merged in 2020-10, with the labels that each got.

#9 frontend: login and signup added
  package-lock.json
  package.json
  src/App.js
  src/Components/ButtomNavigation.js
  src/Components/Navbar.js
  src/Screens/Home.js
  src/Screens/Signin.js
  src/Screens/Signup.js
  src/index.css
Labels: frontend

#11 Backend: Update database schema
  server/model/user.js
  server/routes/authRouteLogin.js
  server/routes/authRouteRegister.js
  server/server.js
Labels: backend

#17 Backend: Endpoints to handle projects
  server/model/user.js
  server/routes/addProject.js
  server/routes/addSession.js
  server/routes/getProject.js
  server/server.js
Labels: backend

#26 issue and pr template added
  .github/PULL_REQUEST_TEMPLATE.md
  .github/issue_template.md
Labels: documentation

#37 Backend: add endpoints for grade and attendance
  server/model/user.js
  server/routes/attendaceManager.js
  server/routes/gradeManager.js
  server/server.js
Labels: backend, enhancement

#42 Frontend: add timer page
  src/App.js
  src/Components/StopWatch.js
  src/Screens/Timer-page.js
  src/Screens/Timer.js
Labels: enhancement, frontend

#43 frontend: integrate backend for authentication
  src/Screens/Landing-Page/Components/NavbarLanding.js
  src/Screens/Signin.js
  src/Screens/Signup.js
Labels: frontend

#44 Frontend: render milestones in view projects page
  src/Screens/ViewProjects.js
Labels: frontend

#46 Frontend: New UI
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/Components/Navbar/Navbar.css
  src/Components/Navbar/Navbar.js
  src/Components/Navbar/NavigationBar.js
  src/Components/Navbar/Sidebar.js
  src/Components/Navbar/SidebarData.js
  src/Components/SetMilestone.css
  src/Screens/NewProject.css
  src/Screens/NewProject.js
  src/Screens/Signin.js
  src/Screens/Signup.js
  src/Screens/Statistics.js
  src/Screens/Timer-page.js
  src/Screens/ViewProjects.js
  src/Styles/App.css
Labels: enhancement, frontend

#47 Frontend: add grade and attendance pages
  src/Components/AddProject.js
  src/Components/Navbar/Sidebar.js
  src/Components/TimerandProjectListButton.js
  src/Screens/attendance.js
  src/Screens/grade.js
  src/childApp.js
Labels: frontend

#48 Frontend: add pictures
  public/Images/grade-m.jpg
  public/Images/new-proj.jpg
  public/Images/timer.jpg
  public/Images/view-proj.jpg
  src/Screens/Grade.js
  src/Screens/NewProject.js
  src/Screens/Timer-page.js
  src/Screens/ViewProjects.js
Labels: enhancement, frontend

#49 Frontend: improvements in signin/signup
  src/Screens/Signin.js
  src/Screens/Signup.js
Labels: enhancement, frontend

#50 Frontend: Changes in landing page
  public/Images/02.jpg
  src/Screens/Landing-Page/Components/Cards.css
  src/Screens/Landing-Page/Components/Cards.js
Labels: enhancement, frontend

#51 Frontend: add new UI and features
  public/Images/02.jpg
  public/Images/grade-m.jpg
  public/Images/new-proj.jpg
  public/Images/timer.jpg
  public/Images/view-proj.jpg
  src/App.js
  src/Components/AddProject.js
  src/Components/Navbar/Sidebar.js
  src/Components/TimerandProjectListButton.js
  src/Screens/Grade.js
  src/Screens/Landing-Page/Components/Cards.css
  src/Screens/Landing-Page/Components/Cards.js
  src/Screens/NewProject.js
  src/Screens/Signin.js
  src/Screens/Signup.js
  src/Screens/Statistics.js
  src/Screens/Timer-page.js
  src/Screens/Timer.js
  src/Screens/ViewProjects.js
  src/childApp.js
Labels: frontend

#52 Frontend: minor changes
  src/Components/Navbar/Sidebar.js
  src/Components/PieChart.js
  src/Components/SetMilestone.js
  src/Screens/Statistics.js
  src/Screens/Timer.js
Labels: frontend

#53 Update README
  README.md
Labels: documentation
